describe ('Skenario Verifikasi Fungsi Login', () => {

    it('TC-001 Verify that the user can log in using a valid username and password', () => {
        cy.visit("https://opensource-demo.orangehrmlive.com/web/index.php/auth/login")
        cy.get('.orangehrm-login-title').should('be.visible')
        cy.get("img[alt='company-branding']").should('be.visible')
        cy.get("input[placeholder='Username']").type('Admin')
        cy.get("input[placeholder='Password']").type('admin123')
        cy.intercept('GET', 'https://opensource-demo.orangehrmlive.com/web/index.php/api/v2/dashboard/employees/action-summary').as('actionSummary')
        cy.get("button[type='submit']").click()
        cy.wait('@actionSummary').its('response.statusCode').should('eq', 200)
        cy.get('.oxd-topbar-header-title').should('have.text' , 'Dashboard')
    })

    it('TC-002 Verify login using an invalid username and valid password', () => {
        cy.visit("https://opensource-demo.orangehrmlive.com/web/index.php/auth/login")
        cy.get('.orangehrm-login-title').should('be.visible')
        cy.get("img[alt='company-branding']").should('be.visible')
        cy.get("input[placeholder='Username']").type('InvalidUsername')
        cy.get("input[placeholder='Password']").type('admin123')
        cy.intercept('GET', 'https://opensource-demo.orangehrmlive.com/web/index.php/core/i18n/messages').as('messages')
        cy.get("button[type='submit']").click()
        cy.wait('@messages').its('response.statusCode').should('eq', 304)
        cy.get('.oxd-alert-content.oxd-alert-content--error').should('be.visible')
    })

    it('TC-003 Verify login using a valid username and invalid password', () => {
        cy.visit("https://opensource-demo.orangehrmlive.com/web/index.php/auth/login")
        cy.get('.orangehrm-login-title').should('be.visible')
        cy.get("img[alt='company-branding']").should('be.visible')
        cy.get("input[placeholder='Username']").type('Admin')
        cy.get("input[placeholder='Password']").type('wrong123')
        cy.intercept('GET', 'https://opensource-demo.orangehrmlive.com/web/index.php/core/i18n/messages').as('messages')
        cy.get("button[type='submit']").click()
        cy.wait('@messages').its('response.statusCode').should('eq', 304)
        cy.get('.oxd-alert-content.oxd-alert-content--error').should('be.visible')
    })

    it('TC-004 Verify login using an invalid username and invalid password', () => {
        cy.visit("https://opensource-demo.orangehrmlive.com/web/index.php/auth/login")
        cy.get('.orangehrm-login-title').should('be.visible')
        cy.get("img[alt='company-branding']").should('be.visible')
        cy.get("input[placeholder='Username']").type('InvalidUsername')
        cy.get("input[placeholder='Password']").type('wrong123')
        cy.intercept('GET', 'https://opensource-demo.orangehrmlive.com/web/index.php/core/i18n/messages').as('messages')
        cy.get("button[type='submit']").click()
        cy.wait('@messages').its('response.statusCode').should('eq', 304)
        cy.get('.oxd-alert-content.oxd-alert-content--error').should('be.visible')
    })

    it('TC-008 Verify login using special characters in username and password', () => {
        cy.visit("https://opensource-demo.orangehrmlive.com/web/index.php/auth/login")
        cy.get('.orangehrm-login-title').should('be.visible')
        cy.get("img[alt='company-branding']").should('be.visible')
        cy.get("input[placeholder='Username']").type("Admin!@")
        cy.get("input[placeholder='Password']").type("admin123!@")
        cy.intercept('GET', 'https://opensource-demo.orangehrmlive.com/web/index.php/core/i18n/messages').as('messages')
        cy.get("button[type='submit']").click()
        cy.wait('@messages').its('response.statusCode').should('eq', 304)
        cy.get('.oxd-alert-content.oxd-alert-content--error').should('be.visible')
    })

    it('TC-009 Verify login using valid credentials with leading and trailing spaces', () => {
        cy.visit("https://opensource-demo.orangehrmlive.com/web/index.php/auth/login")
        cy.get('.orangehrm-login-title').should('be.visible')
        cy.get("img[alt='company-branding']").should('be.visible')
        cy.get("input[placeholder='Username']").type(' Admin ')
        cy.get("input[placeholder='Password']").type(' admin123 ')
        cy.intercept('GET', 'https://opensource-demo.orangehrmlive.com/web/index.php/core/i18n/messages').as('messages')
        cy.get("button[type='submit']").click()
        cy.wait('@messages').its('response.statusCode').should('eq', 304)
        cy.get('.oxd-alert-content.oxd-alert-content--error').should('be.visible')
    })

    it('TC-010 Verify login using a valid username with different letter capitalization', () => {
        cy.visit("https://opensource-demo.orangehrmlive.com/web/index.php/auth/login")
        cy.get('.orangehrm-login-title').should('be.visible')
        cy.get("img[alt='company-branding']").should('be.visible')
        cy.get("input[placeholder='Username']").type('aDmin')
        cy.get("input[placeholder='Password']").type('admin123')
        cy.intercept('GET', 'https://opensource-demo.orangehrmlive.com/web/index.php/api/v2/dashboard/employees/action-summary').as('actionSummary')
        cy.get("button[type='submit']").click()
        cy.wait('@actionSummary').its('response.statusCode').should('eq', 200)
        cy.get('.oxd-topbar-header-title').should('have.text' , 'Dashboard')
    })

    it('TC-011 Verify login using a valid password with different letter capitalization', () => {
        cy.visit("https://opensource-demo.orangehrmlive.com/web/index.php/auth/login")
        cy.get('.orangehrm-login-title').should('be.visible')
        cy.get("img[alt='company-branding']").should('be.visible')
        cy.get("input[placeholder='Username']").type('Admin')
        cy.get("input[placeholder='Password']").type('aDmin123')
        cy.intercept('GET', 'https://opensource-demo.orangehrmlive.com/web/index.php/core/i18n/messages').as('messages')
        cy.get("button[type='submit']").click()
        cy.wait('@messages').its('response.statusCode').should('eq', 304)
        cy.get('.oxd-alert-content.oxd-alert-content--error').should('be.visible')
    })
})